name: Run build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build
        run: |
          uv run ./main.py
          mkdir -p html
          mv index.html html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
